name: Deploy static site to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Zip static site content
        run: zip -r site.zip . -x '*.git*' '*.github*'

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'DolceMadre'  # Asegúrate que este sea el nombre exacto de tu App Service en Azure
          slot-name: 'Production'
          package: site.zip
          
deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4B94982EFC434EB5B82ABB5D8EA7807C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7D837E7816894B74A1DDE560B40569DD }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_EBF34F3C37904731BDE694A5F2D4329C }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'DolceMadre'
          slot-name: 'Production'
          package: .
          
