name: Deploy static site to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Zip static site content
        run: zip -r site.zip . -x '*.git*' '*.github*'

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'DolceMadre'  # Asegúrate que este sea el nombre exacto de tu App Service en Azure
          slot-name: 'Production'
          package: site.zip
          
